BEGIN;

CREATE TABLE IF NOT EXISTS app_alive (
    ID SERIAL NOT NULL,
    APP_NAME VARCHAR(50) NOT NULL, 
    START_DATETIME TIMESTAMP NOT NULL, 
    END_DATETIME TIMESTAMP NOT NULL, 
    LAST_MOD_DATETIME TIMESTAMP NOT NULL,
    CONSTRAINT app_alive_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS app_metrics (
    APP_ALIVE_ID INTEGER NOT NULL,
    CONTENT VARCHAR(4096) NOT NULL,
    DATETIME TIMESTAMP NOT NULL,
    CONSTRAINT app_metrics_fk FOREIGN KEY (APP_ALIVE_ID) REFERENCES app_alive (ID)
);

COMMIT;
