CREATE TABLE IF NOT EXISTS app_alive (
    ID SERIAL NOT NULL CONSTRAINT app_alive_pk PRIMARY KEY,
    APP_NAME VARCHAR(50) NOT NULL, 
    START_DATETIME TIMESTAMP NOT NULL, 
    END_DATETIME TIMESTAMP NOT NULL, 
    LAST_MOD_DATETIME TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS app_metrics (
    APP_ALIVE_ID INTEGER NOT NULL CONSTRAINT app_alive_fk REFERENCES app_alive ON DELETE CASCADE,
    CONTENT VARCHAR(4096) NOT NULL,
    DATETIME TIMESTAMP NOT NULL
);
